CREATE OR REPLACE FUNCTION
MoTypeCreate(varchar) RETURNS int AS 'MODULE_PATHNAME','MoTypeCreate'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION
fteste(varchar) RETURNS int AS 'MODULE_PATHNAME','fteste'
LANGUAGE C STRICT;
