CREATE OR REPLACE FUNCTION
MoTypeCreate(varchar) RETURNS int AS 'MODULE_PATHNAME','MoTypeCreate'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION
MoTypeUpdate(int, varchar) RETURNS int AS 'MODULE_PATHNAME','MoTypeUpdate'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION
MoTypeDelete(int) RETURNS int AS 'MODULE_PATHNAME','MoTypeDelete'
LANGUAGE C STRICT;
